apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  namespace: default
  labels:
    app: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo
        image: anilkuscu95/demo
        imagePullPolicy: Always
        env:
        - name: ASPNETCORE_URLS
          value: "http://+:"                               
        ports:
        - containerPort: 11130
          name: web
---
kind: Service
apiVersion: v1
metadata:
  name: demo-nodeport-service
  namespace: default
spec:
  selector:
    app: demo
  ports:
  - protocol: TCP
    port: 11130
    targetPort: 11130
  type: NodePort
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: demo-hpa
  namespace: default
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: demo
  targetCPUUtilizationPercentage: 80